name: Unit Tests

on:
  push:
    # Check on all branches
    branches:
      - '*'
  schedule:
    - cron: '0 0 */14 * *' # Runs every 14 days

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.8]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install -r httpx==1.0.0.beta0 --force-reinstall
        working-directory: ./

      - name: Run Unit Tests
        run: |
          python -m unittest discover -s tests -p "*_test.py"
        working-directory: ./
